FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build

WORKDIR /app

COPY . .

RUN dotnet build


FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine

WORKDIR /app

COPY --from=build /app/FrameworklessAppKata/bin/Debug/netcoreapp3.1/ .

ENTRYPOINT ["dotnet","FrameworklessAppKata.dll"]