FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

WORKDIR /app

COPY . .

RUN dotnet build


FROM mcr.microsoft.com/dotnet/core/runtime:3.1

WORKDIR /app2

COPY --from=build /app/FrameworklessAppKata/bin/Debug/netcoreapp3.1/ .

EXPOSE 8080

ENTRYPOINT ["dotnet","FrameworklessAppKata.dll"]