steps:
  - label: 'build docker image'
    command:
      - docker build -t frameworkless-app-image .
    agents:
     queue: fma-dev
     
  - label: 'run container and execute unit test'
      command:
        - docker run --name frameworkless-app-container frameworkless-app-image
      agents:
        queue: fma-dev   