steps:
  - label: 'build docker image and run it'
    command:
      - docker build -t frameworkless-app-image .
      - docker run --name frameworkless-app-container frameworkless-app-image
    agents:
     queue: fma-dev