steps:
  - label: 'build docker image and run tests'
    command:
      - docker build -f Dockerfile-Test -t frameworkless-app-test-image .
      - docker run -e SECRET_USERNAME="test-token" frameworkless-app-test-image
    agents:
     queue: katherine-lab
  - wait  
  - label: 'build docker image and publishing it to ECR'
    command:
      - docker build -f Dockerfile-Run -t 741922737521.dkr.ecr.ap-southeast-2.amazonaws.com/samaa-frameworkless-app:$BUILDKITE_BUILD_NUMBER .
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 741922737521.dkr.ecr.ap-southeast-2.amazonaws.com
      - docker push 741922737521.dkr.ecr.ap-southeast-2.amazonaws.com/samaa-frameworkless-app:$BUILDKITE_BUILD_NUMBER
    agents:
      queue: katherine-lab
  - wait
  - label: 'Deploy with Jupiter'
    command:
      - ./Jupiter/deploy.sh
    agents:
      queue: europa-preprod-fma